# Generated by Django 4.2.1 on 2023-05-31 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.CharField(default='La 33', max_length=255),
            preserve_default=False,
        ),
    ]
