# Generated by Django 4.2.1 on 2023-06-05 17:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0004_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='racers',
            field=models.ManyToManyField(blank=True, related_name='racers', to=settings.AUTH_USER_MODEL),
        ),
    ]
