# Generated by Django 4.1.5 on 2023-06-17 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_booking_racers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AlterField(
            model_name='circuit',
            name='photo',
            field=models.ImageField(upload_to='static/images/circuits'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='photo',
            field=models.ImageField(upload_to='static/images/equipment'),
        ),
        migrations.AlterField(
            model_name='kart',
            name='photo',
            field=models.ImageField(upload_to='static/images/cars'),
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='static/images/forecast')),
                ('tempMin', models.IntegerField()),
                ('tempMax', models.IntegerField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.circuit')),
            ],
        ),
    ]
